### ISSUE TITLE
Questions element

### ISSUE THREAD

**Issue by kevin-foreman** [kevin-foreman/script-quiz#2]
# Requirements

## Quiz questions array
* must contain at least 10 questions
* must iterate through the questions as the user answers and provide feedback if they are correct or incorrect
* must penalize the user for selecting a wrong answer

**Comment by kevin-foreman** [comment]
Also must record the user's initials and score

**Comment by thisfardi** [comment]
add time if timeout quiz finish

**Comment by kevin-foreman** [comment]
* Questions array does not have a number of questions requirement

**Comment by kevin-foreman** [comment]
Added an 8 question array, which iterates randomly, and penalizes the user if they select an incorrect answer
